### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by johnedquinn** [ricksbrown/jgenhtml#1]
Hi @ricksbrown ! I'm curious about the licensing of this repository. I'd like to use this project, however, I'm prohibited from leveraging this codebase if certain licenses aren't attached. Please let me know if you have plans to add licensing information to this project!

**Comment by ricksbrown** [comment]
Hi @johnedquinn - thank you for taking the time to write to me. I actually have a bunch of enhancements to this codebase sitting on a local branch somewhere (if I can find it) - I think I totally threw away and re-did the unit testing because it was too complex.

Anyway, does GNU GPLv3 work for you?

**Comment by johnedquinn** [comment]
Thanks for the response! Seeing that the project's last commit was some years ago, I wasn't sure if I'd get a response.

Unfortunately, GNU GPLv3 is currently restricted in the context where I'm using it -- though, I'm working on making an exception. That being said, other licenses are free to use such as: The MIT License, Apacha v2.0, Apache v1.1, and BSD licenses.

**Comment by ricksbrown** [comment]
Yeah I kind of neglected this repo since I stopped using it myself.
I really should give it some love :D

**Comment by johnedquinn** [comment]
I've really enjoyed testing it over the past couple days! Also, for your recent commit, you still have licensing information in your POM. BTW, is there any ETA for your release to Maven? And, if there's anything I can do, I'd be glad to submit PRs!

**Comment by ricksbrown** [comment]
> I've really enjoyed testing it over the past couple days! Also, for your recent commit, you still have licensing information in your POM. BTW, is there any ETA for your release to Maven? And, if there's anything I can do, I'd be glad to submit PRs!

You're brave - the doco is terrible, I can't remember how to use it.
It looks like I put a fair bit of work into it, if it's still useful then I think the first thing to "fix" is the readme :D 

There seem to be some failing unit tests, I'll see if I can work that out too.

BTW it's already in maven, I added it to the readme.

**Comment by johnedquinn** [comment]
Regarding Maven, the GPL license is still associated with [v1.5](https://central.sonatype.com/artifact/com.googlecode.jgenhtml/jgenhtml/1.5)

**Comment by ricksbrown** [comment]
> Regarding Maven, the GPL license is still associated with [v1.5](https://central.sonatype.com/artifact/com.googlecode.jgenhtml/jgenhtml/1.5)

Gotcha!

OK I'll aim to get something out in the next few days.
I need to make it worth my while, so I'll do some minor housekeeping first, like bump up a few dependency versions and move the target off java 1.6

**Comment by ricksbrown** [comment]
Hi @johnedquinn FYI I released 1.6 to Maven Central today. 🎉 
It's actually pretty useful, I might start using it again myself!

Note: the maven config changed a little from 1.5 - example usage is now in the readme.

Have fun with it and thanks for giving me the motivation to finally clean it up after all these years!

**Comment by johnedquinn** [comment]
Thanks so much!! I'll be taking a look today!
